displayName=Preserve & Menaphite Optimiser
author=jtclowner
description=Adds reminders and optimises timing of Preserve prayer and Menaphite remedies to maximise boost duration. Supports regular boosts, divine potions and Saturated Heart.
tags=preserve,menaphite,remedy,divine,potion,boost,heart,saturated heart,timer,reminder,decay,stats
plugins=com.menaphite.MenaphiteRemedyRemindersPlugin
version=1.0.1
build=standard
